# Generated by Django 4.2.30 on 2026-05-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_grupos_subgrupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='producto',
            name='ieps_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='margen_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='no_contabilizable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_calculado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_mandatorio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_sin_impuestos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_venta',
            field=models.CharField(choices=[('PIEZA', 'Pieza'), ('KG', 'Kilogramo')], default='PIEZA', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidades_compra',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='producto',
            name='usar_precio_mandatorio',
            field=models.BooleanField(default=False),
        ),
    ]
