# Generated by Django 4.2.30 on 2026-05-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_producto_costo_compra_producto_ieps_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
