# Generated by Django 4.2.30 on 2026-05-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_producto_stock_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ieps_porcentaje',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=5),
        ),
    ]
