# Generated by Django 4.2.30 on 2026-05-23 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_cajaturno_venta_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=180)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('regimen_fiscal', models.CharField(blank=True, default='', max_length=120)),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=10)),
                ('uso_cfdi', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('tipo_persona', models.CharField(choices=[('FISICA', 'Persona fisica'), ('MORAL', 'Persona moral')], default='FISICA', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['razon_social'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='retencion_isr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_ieps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='base_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='base_unitaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='ieps_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='ieps_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='iva_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='iva_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='sales.clientefiscal'),
        ),
    ]
