# Generated by Django 4.2.30 on 2026-05-23 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_alter_producto_ieps_porcentaje'),
        ('sales', '0003_clientefiscal_venta_retencion_isr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaSinStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('stock_disponible', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cantidad_faltante', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltantes_stock', to='sales.venta')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
